132
a:4:{s:8:"template";a:1:{s:10:"footer.tpl";b:1;}s:9:"timestamp";i:1184695283;s:7:"expires";i:1184695283;s:13:"cache_serials";a:0:{}}<div id="footer">
	<a href="rss.php"><img src="img/rss.png" alt="RSS" /></a>
    &copy;2007 <a href="http://www.steel-software.com">Steel Software</a> | <a href="tnc.php">Terms &amp; Conditions</a> | <a href="mailto:webmaster@sheffieldhockey.com">Contact Us</a> | <a href="mailto:steve@steel-software.com?subject=Feature request">Request a Feature</a> | Current Version: v4.00 BETA <br />
Generated by USE-FULL in 0.121 seconds</div>
</div></div></div><div class="bb"><div></div></div></div>
</div>
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2193226-1";
urchinTracker();
</script>
</body>
</html>