 <div id="siteInfo"> <a href="rss.php"><img src="img/rss.png" alt="RSS" border="0" /></a> <a href="information.php?PageID=4">About Us</a> | <a href="mailto:webmaster@sheffieldhockey.com">Contact Us</a> | <a href="mailto:girder@sheffieldhockey.com?subject=Feature request">Request a Feature</a> | &copy;2007 <a href="http://www.steel-software.com">Steel Software</a> | Current Version: v3.06 <br />
<?php
$round = 3; // The number of decimal places to round the micro time to.
$m_time = explode(" ",microtime());
$m_time = $m_time[0] + $m_time[1];
$endtime = $m_time;
$totaltime = ($endtime - $starttime);
echo "Generated by USE-FULL in ". round($totaltime,$round) ." seconds"; ?></div>

<div style="padding: 0px 10px 5px 10px;">
    <a href="http://validator.w3.org/check?uri=referer">
	<img src="img/logo-xhtml.png"
        alt="Valid XHTML 1.0 Transitional" border="0" /></a>
		 <a href="http://jigsaw.w3.org/css-validator/">
    <img style="border:0;"
       src="img/logo-css.png" 
       alt="Valid CSS!" /></a>
 </div>
</div>
</body>
</html>