<div id="footer">
	<a href="rss.php"><img src="img/rss.png" alt="RSS" /></a>
    &copy;2008 <a href="http://www.steveworkman.com">Steve Workman</a> | <a href="tnc.php">Terms &amp; Conditions</a> | {mailto address=$webmaster encode=javascript text="Contact Us"} | {mailto address="steve@steveworkman.com" encode=javascript subject="Feature request" text="Request a feature"}<br />
Generated by USE v4.13 in {$rendertime} seconds</div>
</div></div></div><div class="bb"><div></div></div></div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2193226-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
</body>
</html>