<?php /* Smarty version 2.6.18, created on 2009-09-02 20:33:25
         compiled from footer.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'mailto', 'footer.tpl', 3, false),)), $this); ?>
<div id="footer">
	<a href="rss.php"><img src="img/rss.png" alt="RSS" /></a>
    &copy;2008 <a href="http://www.steveworkman.com">Steve Workman</a> | <a href="tnc.php">Terms &amp; Conditions</a> | <?php echo smarty_function_mailto(array('address' => $this->_tpl_vars['webmaster'],'encode' => 'javascript','text' => 'Contact Us'), $this);?>
 | <?php echo smarty_function_mailto(array('address' => "steve@steveworkman.com",'encode' => 'javascript','subject' => 'Feature request','text' => 'Request a feature'), $this);?>
<br />
Generated by USE v4.12 in <?php echo $this->_tpl_vars['rendertime']; ?>
 seconds</div>
</div></div></div><div class="bb"><div></div></div></div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-2193226-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
</body>
</html>